### PR TITLE
Implement camera bounds-based animation and easing with V10 SDK

### PR DESCRIPTION
**Pull request by naftalibeder**
## Description

Implements camera bounds-based animation and easing using the V10 SDK. Currently implemented only on iOS, and I can port it to Android if there's agreement that this can be merged into `main`.

## Checklist

- [X] I have tested this on a device/simulator for each compatible OS (iOS only right now)
- [X] I formatted JS and TS files with running `yarn lint:fix` in the root folder
- [X] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] ~I updated the typings files (`index.d.ts`)~ (N/A)
- [X] I added/ updated a sample (`/example`)

## Video

https://user-images.githubusercontent.com/2423291/163045880-9d5c1ff3-741e-481f-9261-0f293d9f01b2.mov

### CODE REVIEW

**Review by mfazekas — APPROVED** [review]
@naftalibeder thanks this looks good to me, thanks much for the patch!

**Comment by naftalibeder** [comment]
@mfazekas Sorry, I should have clarified - this could probably have been considered a work in progress (missing Android, as well as padding - in fact, I have a small refactor on the iOS side in progress to allow that).

I don’t know if you want to revert the merge, or if I should just open a new PR, but reopening this PR might produce a cleaner history.

**Comment by mfazekas** [comment]
@naftalibeder, sorry for that. I think it's already an improvement, feel free to open a new PR.

**Comment by naftalibeder** [comment]
No worries! Thanks :)

**Comment by mfazekas** [comment]
@naftalibeder I also has some improvements for v10 iOS side of camera, based on your work at #1835. Hopefully you can merge it with your newer changes.

**Pull request merged**
