### PR TITLE
Fixed expo plugin for android

### PR DESCRIPTION
**Pull request by VolkerLieber**
`addMapboxMavenRepo` was inserting at the wrong position

- [X] I have tested this on a device/simulator for each compatible OS
- [X] I updated the documentation with running `yarn generate` in the root folder
- [X] I updated the typings files - if js interface was changed (`index.d.ts`)
- [X] I added/ updated a sample - if a new feature was implemented (`/example`)

### CODE REVIEW

**Comment by fabio-alss-freitas** [comment]
Good job, tested and worked!

**Review by fabio-alss-freitas — APPROVED** [review]

**Review by mfazekas — APPROVED** [review]

**Comment by mfazekas** [comment]
Thanks, can you look into the build failures https://github.com/rnmapbox/maps/actions/runs/3401058480/jobs/5660517205

**Comment by VolkerLieber** [comment]
`There are unstaged changes in the generated code. Please add them to your commit` is the error message

**Comment by VolkerLieber** [comment]
It should be fixed now

**Review by fabio-alss-freitas — APPROVED** [review]

**Review by mfazekas — APPROVED** [review]

**Comment by fabio-alss-freitas** [comment]
@mfazekas Can you help us with that? It is making it impossible to deploy Expo applications

**Comment by VolkerLieber** [comment]
That was because of another difference it seems. I'm sorry, I can't rebuild it correctly atm since I'm not in the office and can only edit the file on my mobile phone until tomorrow

**Comment by Dakuan** [comment]
Could this be whats broken all our Android builds?

image

**Comment by Dakuan** [comment]
upgrading to latest gives me this:

image

**Comment by VolkerLieber** [comment]
Can you please check your package.json?
The last screenshot looks like maybe the library is not correctly defined in `package.json`.
Something like this: `"undefined":"rnmapbox/maps#main`

**Comment by VolkerLieber** [comment]
> Could this be whats broken all our Android builds? as of this afternoon (GMT)
> 
> image
> 

That's the error I got before this fix

**Comment by Dakuan** [comment]
image

**Comment by Dakuan** [comment]
previously had it pinned to a commit

image

**Comment by VolkerLieber** [comment]
Ah ok, could you please `npx expo prebuild` and post the `build.gradle`?
Since I don't know how old the pinned version was, what's the SDK type set for the expo plugin (in `app.json` I think)?

**Comment by Dakuan** [comment]
```
➜  app git:(main) ✗ expo prebuild
Failed to resolve plugin for module "@rnmapbox/maps" relative to "/Users/dom/git/birda/app"
```

image

we are on expo 45

**Comment by Dakuan** [comment]
build .grade from the pinned version
```
import org.apache.tools.ant.taskdefs.condition.Os

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = findProperty('android.buildToolsVersion') ?: '31.0.0'
        minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '21')
        compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '31')
        targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '31')
        if (findProperty('android.kotlinVersion')) {
            kotlinVersion = findProperty('android.kotlinVersion')
        }
        frescoVersion = findProperty('expo.frescoVersion') ?: '2.5.0'

        if (System.properties['os.arch'] == 'aarch64') {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = '24.0.8215888'
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = '21.4.7075529'
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.3.3'
        classpath('com.android.tools.build:gradle:7.0.4')
        classpath('com.facebook.react:react-native-gradle-plugin')
        classpath('de.undercouch:gradle-download-task:4.1.2')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
// @generated begin @rnmapbox/maps-v2-maven - expo prebuild (DO NOT MODIFY) sync-cb5ce5d6dd5aff6f68a082fbcf1a84c114ee0ce9
maven {
      url 'https://api.mapbox.com/downloads/v2/releases/maven'
      authentication { basic(BasicAuthentication) }
      credentials {
        username = 'mapbox'
        password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
      }
    }
// @generated end @rnmapbox/maps-v2-maven
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url(new File(['node', '--print', "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), '../android'))
        }
        maven {
            // Android JSC is installed from npm
            url(new File(['node', '--print', "require.resolve('jsc-android/package.json')"].execute(null, rootDir).text.trim(), '../dist'))
        }

        google()
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup 'com.facebook.react'
            }
        }
        maven { url 'https://www.jitpack.io' }
    }
}
```

**Comment by VolkerLieber** [comment]
Thank you, I'll look into it tomorrow as soon as I'm in my office.
Until then, I have two more ideas to try:
Update the rnmapbox package again. This fix was merged into main an hour ago, so maybe you downloaded the bugged version from before.
If that doesn't work, maybe try `mapbox` instead of `mapbox-gl` since it will be dropped soon (according to the documentation)

**Comment by fabio-alss-freitas** [comment]
> Could this be whats broken all our Android builds? as of this afternoon (GMT)
> 
> image

Yes, this is the error that us faced.

Now my build.gradle, after run expo prebuild is:

`import org.apache.tools.ant.taskdefs.condition.Os

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        buildToolsVersion = findProperty('android.buildToolsVersion') ?: '31.0.0'
        minSdkVersion = Integer.parseInt(findProperty('android.minSdkVersion') ?: '21')
        compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '31')
        targetSdkVersion = Integer.parseInt(findProperty('android.targetSdkVersion') ?: '31')
        if (findProperty('android.kotlinVersion')) {
            kotlinVersion = findProperty('android.kotlinVersion')
        }
        frescoVersion = findProperty('expo.frescoVersion') ?: '2.5.0'

        if (System.properties['os.arch'] == 'aarch64') {
            // For M1 Users we need to use the NDK 24 which added support for aarch64
            ndkVersion = '24.0.8215888'
        } else {
            // Otherwise we default to the side-by-side NDK version from AGP.
            ndkVersion = '21.4.7075529'
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.3.3'
        classpath('com.android.tools.build:gradle:7.1.1')
        classpath('com.facebook.react:react-native-gradle-plugin')
        classpath('de.undercouch:gradle-download-task:5.0.1')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

def REACT_NATIVE_VERSION = new File(['node', '--print',"JSON.parse(require('fs').readFileSync(require.resolve('react-native/package.json'), 'utf-8')).version"].execute(null, rootDir).text.trim())

allprojects {
    configurations.all {
        resolutionStrategy {
            force "com.facebook.react:react-native:" + REACT_NATIVE_VERSION
        }
    }

    repositories {
        // @generated begin @rnmapbox/maps-v2-maven - expo prebuild (DO NOT MODIFY) sync-cb5ce5d6dd5aff6f68a082fbcf1a84c114ee0ce9
maven {
      url 'https://api.mapbox.com/downloads/v2/releases/maven'
      authentication { basic(BasicAuthentication) }
      credentials {
        username = 'mapbox'
        password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
      }
    }
// @generated end @rnmapbox/maps-v2-maven
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url(new File(['node', '--print', "require.resolve('react-native/package.json')"].execute(null, rootDir).text.trim(), '../android'))
        }
        maven {
            // Android JSC is installed from npm
            url(new File(['node', '--print', "require.resolve('jsc-android/package.json')"].execute(null, rootDir).text.trim(), '../dist'))
        }

        google()
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup 'com.facebook.react'
            }
        }
        maven { url 'https://www.jitpack.io' }
    }
}

configurations.all {
  resolutionStrategy {
    force 'com.facebook.react:react-native:0.69.6'
  }
}`

Try to install the #main using npm.

**Comment by Dakuan** [comment]
```
➜  app git:(main) ✗ rm -rf node_modules

➜  app git:(main) ✗ yarn add rnmapbox/maps#main
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
warning Resolution field "react-devtools-core@4.6.0" is incompatible with requested version "react-devtools-core@^4.23.0"
--- SNIP ---
$ patch-package
patch-package 6.4.7
Applying patches...
eslint-plugin-react-native@4.0.0 ✔
expo-auth-session@3.6.1 ✔
h3-js@3.7.2 ✔
$ husky install
husky - Git hooks installed
✨  Done in 44.10s.

➜  app git:(main) ✗ eas build --local
✔ Select platform › Android
    PluginError: Failed to resolve plugin for module "@rnmapbox/maps" relative to
    "/Users/dom/git/birda/app"
    Code: PLUGIN_NOT_FOUND
```

**Comment by VolkerLieber** [comment]
So the pinned version suddenly failed and that was the reason to update?
Maybe your mapbox token did get cancelled?
That is the only other possibility I can think of atm for this scenario.

**Comment by Dakuan** [comment]
correct, builds failed this afternoon, since the v10 re-write this package is on our naughty list for unexpectedly failing (sorry!) so checked the issues and found this one. I'll see about the token tomorrow, seems unlikely tho!

**Comment by Dakuan** [comment]
also tried a fresh app

```
➜  RNMapbox git:(main) ✗ npx create-expo-app RNMapbox

➜  RNMapbox git:(main) ✗ cd RNMapbox

➜  RNMapbox git:(main) ✗ expo install rnmapbox/maps#main

*** add config plugin setup ***

➜  RNMapbox git:(main) ✗ eas build --local
✔ Select platform › Android
✔ Generated eas.json
    PluginError: Failed to resolve plugin for module
    "@rnmapbox/maps" relative to "/Users/dom/git/RNMapbox"
    Code: PLUGIN_NOT_FOUND
```

**Comment by Dakuan** [comment]
Dug into the expo cli internals....error is being thrown here https://github.com/expo/expo/blob/082815dcf3e2de29c76f7628844ae50a987263a6/packages/%40expo/config-plugins/src/utils/plugin-resolver.ts

made a quick script to see what the https://www.npmjs.com/package/resolve-from package is doing:

```
import resolveFrom from "resolve-from";

const resolved = resolveFrom(
  "/Users/dom/git/RNMapbox",
  "@rnmapbox/maps"
);

console.log("res", resolved);
```

It's throwing this error:

```
Error: Cannot find module '/Users/dom/git/RNMapbox/node_modules/@rnmapbox/maps/lib/commonjs/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/dom/.nvm/versions/node/v16.16.0/lib/node_modules/ts-node/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at resolveFileName (/Users/dom/git/RNMapbox/node_modules/resolve-from/index.js:30:39)
    at resolveFrom (/Users/dom/git/RNMapbox/node_modules/resolve-from/index.js:45:9)
    at module.exports (/Users/dom/git/RNMapbox/node_modules/resolve-from/index.js:48:47)
    at Object.<anonymous> (/Users/dom/git/RNMapbox/resolve.ts:3:29)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/Users/dom/.nvm/versions/node/v16.16.0/lib/node_modules/ts-node/src/index.ts:1597:23) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/dom/git/RNMapbox/node_modules/@rnmapbox/maps/package.json',
  requestPath: '@rnmapbox/maps'
}
```

**Comment by Dakuan** [comment]
@VolkerLieber @mfazekas should I move all of this to a new issue or are we good to carry on here?

**Comment by Dakuan** [comment]
Seems to be related to yarn.

fs installed with yarn:
image


fs installed with npm:

image

**Comment by VolkerLieber** [comment]
`npx create-expo-app -t expo-template-blank-typescript`
`npx expo install rnmapbox/maps#main`

Had to change `"undefined": "rnmapbox/maps#main",` to `"rnmapbox-maps": "rnmapbox/maps#main",` in `package.json` and rename the folder in `node_modules` accordingly

`"plugins": [
      [
        "rnmapbox-maps",
        {
          "RNMapboxMapsImpl": "mapbox",
          "RNMapboxMapsDownloadToken": "sk...."
        }
      ]
    ],`
in `app.json`

`npx expo install`
`eas build`

image

It doesn't seem to be a problem with this commit, so a new ticket would probably be the best.

**Comment by Dakuan** [comment]
Apologies for the spam, the engineer who first reported this to me has our builds working again with `“@rnmapbox/maps”: “^10.0.0-beta.56"`. This means it's no longer an emergency for us (blocking major release). We'll still need to manually test and browser stack the heck out of everything again but hey ho.

**Pull request merged**
