### PR TITLE
Autoformat entire codebase with eslint and prettier

### LINKED ISSUE #1859: Auto-formatting entire codebase
In https://github.com/rnmapbox/maps/pull/1858, @KiwiKilian has kindly set up an auto-formatter to run on staged files, which will make the repo’s code style more consistent and reduce the size of diffs.

In my opinion it makes sense to convert all the source code at once, while nobody has any open PRs, to avoid rough merge conflicts.

Any objections to picking a particular time, possibly a week or two in the future? That way any contributors can be prepared.

### PR DESCRIPTION
**Pull request by KiwiKilian**
## Description

Fixes #1859

I prepared the configs for the reformat of the codebase. When ready to hit with the sledgehammer we have to run `npm run lint:fix` and also fix some errors manually, because `index.d.ts` and `scripts` where completely ignored by `.eslintignore`.

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [x] I updated the documentation with running `yarn generate` in the root folder
- [ ] ~I mentioned this change in `CHANGELOG.md`~
- [x] I updated the typings files (`index.d.ts`)
- [ ] ~I added/ updated a sample (`/example`)~

### CODE REVIEW

**Comment by naftalibeder** [comment]
Awesome! I think we could just rip the band-aid/sledgehammer off.

@mfazekas @rastapasta I believe this pulls in all the recent contributors - does anybody have any running edits that aren't in an open PR?

@KiwiKilian Would you want to run the script and make the fixes you described? I'm not sure how much work that'll be. When do you have some free time to do so? I genuinely thinking we could merge it in today.

**Comment by KiwiKilian** [comment]
As I'm in Europe I will start with it tomorrow morning 👍

**Comment by KiwiKilian** [comment]
I did the following:

1. Merged `main` in to the branch
2. Ran `npm run lint:fix`, sorting out all the prettier errors
3. Fixed remaining errors by hand

I used separated the commits, so auto fixing and manual can be properly viewed. From my point of view its ready to merge.

Current `npm run lint` result:
```
176 problems (0 errors, 176 warnings)
```

From here on we can work towards zero warnings ;).

**Review by mfazekas — APPROVED** [review]

**Comment by naftalibeder** [comment]
Awesome! Not that I doubt `prettier` but… did you also run the example project manually just to be sure everything generally works?

Then, I’d be delighted to merge this 🥰

**Comment by mfazekas** [comment]
@naftalibeder CI is not running now on this probably as it's from a fork:
- I've added the PR to rever the changes likely caused the issue with CI
- We might want to merge to a branch in our repot and merge that branch to main, so we see CI pass first.

**Comment by KiwiKilian** [comment]
The example runs fine for iOS and Android in Simulator for me! 😄

**Pull request merged**
