### PR TITLE
chore: rename everything from rctmgl to rnmbx

### PR DESCRIPTION
**Pull request by WoLewicki**
## Description

PR changing all of the names of components from `RCTMGL` to `RNMBX` including all the generators, folders etc.

## Checklist

- [ ] I have tested this on a device/simulator for each compatible OS
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I added/updated a sample - if a new feature was implemented (`/example`)

### CODE REVIEW

**Comment by mfazekas** [comment]
@WoLewicki can you look into the tests? They are failing `yarn jest`

**Comment by MichaelDanielTom** [comment]
Since we're on the cusp of new versions (MapboxMaps 10 -> 11) and are already doing some renaming, what is everyone's thoughts on keeping the latest versions' code not having prefixes/suffixes, and only after something is outdated does it include prefixes/suffixes if unavoidable? For example, I feel like it's already confusing that everything in RCTMGL-v10 is the actual new code being worked on as opposed to just RCTMGL, which will only get worse with mapbox v11, v12, etc.

**Comment by mfazekas** [comment]
> Since we're on the cusp of new versions (MapboxMaps 10 -> 11) and are already doing some renaming, what is everyone's thoughts on keeping the latest versions' code not having prefixes/suffixes, and only after something is outdated does it include prefixes/suffixes if unavoidable? For example, I feel like it's already confusing that everything in RCTMGL-v10 is the actual new code being worked on as opposed to just RCTMGL, which will only get worse with mapbox v11, v12, etc.

The reason for renaming is that "RCT" prefix is reserved for[ internal react-native components](https://github.com/react-native-camera/react-native-camera/issues/283). `MGL` prefix is outdated as well as GL refers to OpenGL which is no longer used on iOS. We also could get away without any prefixes, as swift and java has namespaces, but ObjC doesn't, so I think the simplest one is using the RNMBX prefix for now.

I do agree that it sound like a good time to remove the `-v10` from the folders. 
Also using `com.mapbox.rnmbx` on android is a bit confusing as it's not a Mapbox project, but I'm not sure what's the best alternative, maybe just `rnmapbox.rnmbx`

But I personally don't feel very strongly about naming. This is a legacy codebase, and there are a lot of issues with the code, naming is the least important for me.

**Comment by WoLewicki** [comment]
@mfazekas  tests should be good now.

**Comment by mfazekas** [comment]
@WoLewicki thanks I'll try to merge tonight. Do you mind the other renaming suggested here?

In directories:
`java-v10` => `java` 
`RNMBX-v10` => `RNMBX'

And moving the java namespace from `com.mapbox.rnbmx' to `rnmabpox.rnmbx` ?

**Comment by WoLewicki** [comment]
So should I remove `com` or did you mean `com.rnmabpox.rnmbx`? I pushed a change with the `com.rnmabpox.rnmbx` and the other requested changes.

**Comment by mfazekas** [comment]
> So should I remove `com` or did you mean `com.rnmabpox.rnmbx`? I pushed a change with the `com.rnmabpox.rnmbx` and the other requested changes.

I was thinking of the one without '.com' as we don't have the rnmabpox domain, but it should be good as is, the issue was that since it's not an official mapbox library we shouldn't be using the com.mapbox namespace.

**Comment by WoLewicki** [comment]
Hey, I have a question. I can see you are merging my PRs through making another PR with all the commits from my PR and then merging them. This way I am not the author of the commit and not added as a contributor. Is it done on purpose @mfazekas ?

**Comment by mfazekas** [comment]
@WoLewicki So the issue is that because actions are using GitHub secrets it's not running for branches outside. Since Mapbox SDK needs access token, only basic test are running for PR-s from forks.

That's why I cloned/tested your PR. You should be marked as contributor, but GH adds my name as well.

Let me know if you have suggestions about that. I'll try to add you as a contributor to the repo, so you CI can run on your PR-s.

**Comment by WoLewicki** [comment]
Hmm I am not too familiar with CI setups, but is there no option to run the CI on the other branch with all the changes that is made by you and then eventually merge the original PR? Or is it dangerous in any sense? I cannot see myself in the contributors: https://github.com/rnmapbox/maps/graphs/contributors and looks like I am only a coauthor of the commit: https://github.com/rnmapbox/maps/commit/c72d4da9c35979dc507667b2f1fe10cde5e8d66f so it can be discouraging for new contributors to the library.

**Comment by WoLewicki** [comment]
And thanks for adding me as a contributor 🚀

**Comment by mfazekas** [comment]
@WoLewicki Sorry I don't know about details of GitHub contributors graph. I think you should show up. I did see a "Contributor" badge in GitHub comment, where I now see member. 

image

And your name is on the commit. 
image

So not sure why you're not on contributors graph.


Yep I could have pressed the merge on your pr in this case. In a lot of cases I also add smaller changes to the PR, so I usually merge mine and close the authors. I wasn't aware that it has effect on contributors graphs:
The process is described here:
https://web.archive.org/web/20160622033602/http://blog.spreedly.com/2014/06/24/merge-pull-request-considered-harmful/#.V2oHqC3P1qY

**Pull request closed without merging**
