### PR TITLE
migrate whole library to new arch

### PR DESCRIPTION
**Pull request by WoLewicki**
## Description

PR with all the changes for migration to new arch gathered together.

## Checklist

- [ ] I have tested this on a device/simulator for each compatible OS
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I added/updated a sample - if a new feature was implemented (`/example`)

### CODE REVIEW

**Comment by mfazekas** [comment]
@WoLewicki thank much for the effort. I'm a bit concerned about the amount of changes. It will be very hard to review/manage this.

Also please use RNMBX prefix instead of MBX as `MBX` prefix is already used  by some Mapbox components.

**Comment by WoLewicki** [comment]
This PR is just a draft with all the changes I make. We will for sure split it to smaller PRs so it is much easier to test and review. I'll also change the names of components 🚀

**Comment by mfazekas** [comment]
> This PR is just a draft with all the changes I make. We will for sure split it to smaller PRs so it is much easier to test and review. I'll also change the names of components 🚀

Cool that sounds great. One issue is that I'm working on supporting the v11 api. See #3040, not sure what's the best way to make merges easier for both of us.

**Comment by WoLewicki** [comment]
I think we can handle it in each component one-by-one when migrating them.

**Comment by mfazekas** [comment]
> I think we can handle it in each component one-by-one when migrating them.

👍

**Comment by WoLewicki** [comment]
Closing in favor of many other PRs based on this one :rocket:

**Pull request closed without merging**
