### PR TITLE
fix: fix kotlin corutines to 1.8.0 instead of binding to kotlin version

### PR DESCRIPTION
**Pull request by mfazekas**
See https://github.com/rnmapbox/maps/pull/3431/files#r1581840316

### CODE REVIEW

**Comment by doneill** [comment]
@mfazekas I understand this has merged, but as I go through the upgrade process upgrading from to 10.1.20 results in the following android build error: 

```
@rnmapbox/maps/android/src/main/mapbox-v11-compat/v10/com/rnmapbox/rnmbx/v11compat/style.kt: (8, 12): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.

The class is loaded from ~/.gradle/caches/transforms-3/5301fd306cdd65a0f7429a13a752c2d3/transformed/jetified-kotlin-stdlib-1.9.21.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rnmapbox_maps:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```

Was this encountered during the development process? Any ideas on a fix?

**Comment by mfazekas** [comment]
@doneill what is your kotlin version? Also is this happens with the latest version[v10.1.27](https://github.com/rnmapbox/maps/releases/tag/v10.1.27)?

**Comment by doneill** [comment]
Kotlin plugin version: `232-1.9.0-release-358-AS10227.8.2321.11231672` 
kotlinc -version ` kotlinc-jvm 2.0.0 (JRE 11.0.2+9)`

**Comment by doneill** [comment]
@mfazekas added ` kotlinVersion = "1.9.22"` and got past the build issue, thanks for the suggestion on kotlin version.

**Pull request merged**
