### PR TITLE
Implement clustering properties to ShapeSource

### PR DESCRIPTION
**Pull request by ivari**
## Description

Years ago, Mapbox implemented `clusterProperties` attribute for `ShapeSource`, which enables declaring custom aggregated properties for clustered features on the map.

Android: https://github.com/mapbox/mapbox-gl-native/pull/15425
iOS: https://github.com/mapbox/mapbox-gl-native/pull/15515

I wanted to see this implemented, as we have a use case in our app where we want to open a new view on cluster tap, which shows information for all features clustered under the icon. Additionally, we want to show information on the icon which is more complex than simple `{point_count}`.

So, finally, we got around to implementing it. Here's the PR.

The fork is already running in production for our apps as well.

Relevant feature request: #693 

## Checklist

- [X] I have tested this on a device/simulator for each compatible OS
- [X] I formatted JS and TS files with running `yarn lint:fix` in the root folder
- [X] I updated the documentation with running `yarn generate` in the root folder
- [x] I mentioned this change in `CHANGELOG.md`
- [X] I updated the typings files (`index.d.ts`)
- [X] I added/ updated a sample (`/example`)

## Screenshot OR Video

See the video from our implementation in our B2B app.
https://user-images.githubusercontent.com/5424427/154564667-1ea37d1e-e9e7-4377-9faf-c5c6090c7530.mov

### CODE REVIEW

**Review by mfazekas — APPROVED** [review]
👍 Thanks very much, looks great, to me. Can you update with current main?!

**Comment by ivari** [comment]
> 👍 Thanks very much, looks great, to me. Can you update with current main?!

Thank you! Rebased to latest main.

**Comment by mfazekas** [comment]
@ivari I'm sorry can you rebase again?! Also can you extend a note in README that it was implemented on maplibre/mapbox-gl

**Comment by naftalibeder** [comment]
@ivari If you don’t mind doing the couple of things @mfazekas mentioned, we can merge this right away. Thanks!

**Comment by ivari** [comment]
@mfazekas, @naftalibeder, my apologies, was on sick leave for a week. Done as you requested, now.

**Comment by WoodburyShortridge** [comment]
@ivari amazing thanks for this!

Do you mind sharing a basic example of usage. Im unable to get it to work. Here's what I got:

```
<ShapeSource
  id="source"
  hitbox={symbolHitbox}
  shape={featureCollection}
  cluster={true}
  clusterMaxZoom={14}
  clusterRadius={50}
  clusterProperties= {{
	  "sum": ["+", ["get", "count"]] // count is a features.properties key on faetureCollection geojson. value is type int
  }}
  >
  <SymbolLayer
	  id="avatarPoints"
	  style={symbolStyle}
	  filter={['!', ['has', 'point_count']]}
  />
  <SymbolLayer
	  id="pointCount"
	  style={pointCountStyle}
  />
  <CircleLayer
	  id="clusteredSymbol"
	  belowLayerID="pointCount"
	  filter={['has', 'point_count']}
	  style={clusterSymbolStyle}
  />
</ShapeSource>
```
and pointCountStyle:

```
const pointCountStyle = {
	textField: '{point_count}-{sum}', // sum is does not exist here
	textSize: 12,
	textColor: 'white',
	textPitchAlignment: 'map'
};
```

**Comment by ivari** [comment]
@WoodburyShortridge please see example at `example/src/examples/SymbolCircleLayer/EarthQuakes.js`

From first glance, the problem you are having is that you are using the short-hand `["+", ["get", "count"]]`. Please instead use the full accumulator definition for adding up the values, as in the example.

I'll be honest here and say that my teams Obj-C skills were not enough to implement the short-hand on iOS. I'd love to see someone take our code and fix that, but until then you can get the exact result you need with just a bit of extra boilerplate.

**Comment by WoodburyShortridge** [comment]
thanks @ivari makes sense. I've changed it to use the accumulated def `sum: [["+", ["accumulated"], ["get", "sum"]], ["get", "count"]]` however I'm still not getting the cluster property `sum` on the symbol layer at all.

I'm at the latests from `rnmapbox/maps#main` and `$RNMapboxMapsVersion = '~> 10.5.0-beta1'`

Is there something else I am missing here? Really appreciate your help and thanks again for the PR and pointing me to the example app 👍 !

Feature collection:
```
const featureCollection = {
'type': 'FeatureCollection',
'features': data.map(d => ({
	'type': 'Feature',
	'properties': {
		'iconSize': .5,
		'count': d.count, // int
	},
	'geometry': d.loc,
	'id': d.id,
})),
};
```

Shape source:
```
<ShapeSource
  id="source"
  hitbox={symbolHitbox}
  shape={featureCollection}
  cluster={true}
  clusterMaxZoom={14}
  clusterRadius={50}
  clusterProperties= {{
	  sum: [["+", ["accumulated"], ["get", "sum"]], ["get", "count"]]
  }}
  >
  <SymbolLayer
	  id="avatarPoints"
	  style={symbolStyle}
	  filter={['!', ['has', 'point_count']]}
  />
  <SymbolLayer
	  id="pointCount"
	  style={pointCountStyle}
  />
  <CircleLayer
	  id="clusteredSymbol"
	  belowLayerID="pointCount"
	  filter={['has', 'point_count']}
	  style={clusterSymbolStyle}
  />
</ShapeSource>
```

Point count style:
```
const pointCountStyle = {
	textField: ['get', 'sum'], // nothing here
	// textField: ['get', 'point_count'], // this works
	textSize: 12,
	textColor: 'white',
	textPitchAlignment: 'map',
};
```

**Comment by ivari** [comment]
@WoodburyShortridge sorry to disappoint you even further. We use `$RNMapboxMapsVersion = '~> 5.9.0'`. Never tried on 10. I can only assume it doesn't work on 10 as is. 🙁

**Comment by WoodburyShortridge** [comment]
ahhh gotcha thanks @ivari 🙁. @mfazekas any insight into why this may not work on more recent versions?

**Comment by mfazekas** [comment]
@WoodburyShortridge can you add an issue for that?! It's just not yet implemented for v10 mapbox versions yet. Shouldn't be hard to implement.

**Comment by ahardy42** [comment]
is this implemented on the v8 branch? I don't see this clusterProperties prop used in the Earthquake example file. I can't get it to work in my project, and I'm not sure if it's just that I'm terrible with Mapbox expressions.

**Comment by mfazekas** [comment]
@ahardy42 I'm sure it's on `#main` so test with that

**Pull request merged**
