### PR TITLE
Autoformat entire codebase

### PR DESCRIPTION
**Pull request by naftalibeder**
From #1859, see https://github.com/rnmapbox/maps/pull/1869#issuecomment-1109735266.

### CODE REVIEW

**Comment by naftalibeder** [comment]
@mfazekas do you know why there are no automatic actions on this PR? I'm not sure exactly where the breaking point is.

**Comment by naftalibeder** [comment]
Tests pass locally for me, and everything I can think of checks out! Going to merge this. :)

@KiwiKilian Thanks for all the effort you put into this!

**Comment by mfazekas** [comment]
@naftalibeder  see https://github.com/rnmapbox/maps/actions/runs/2234384116

also https://github.com/rnmapbox/maps/pull/1869#issuecomment-1109735266 and https://github.com/rnmapbox/maps/pull/1870

image

**Comment by KiwiKilian** [comment]
Thanks for the quick decisions and merge!

**Pull request merged**
