### PR TITLE
Improve EarthQuakes example

### PR DESCRIPTION
**Pull request by KiwiKilian**
## Description

- Transform earthquakes example to TypeScript and Function Component
- Now also displays unclustered point data

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [x] I updated the documentation with running `yarn generate` in the root folder
- [x] I updated the typings files - if js interface was changed (`index.d.ts`)
- [x] I added/ updated a sample - if a new feature was implemented (`/example`)

### CODE REVIEW

**Comment by KiwiKilian** [comment]
I'm having two problems I might need a little help:
- I can't a find to properly type the `ShapeSource` ref
- What is the successor of `SymbolLayerStyle` if it's deprecated?

**Comment by KiwiKilian** [comment]
Also there seems to be a mix of usages in importing the components in the repo. Which is prefered: `<MapView />` or `  <MapboxGL.MapView />`. Would probably be easier for beginners if it's a more unified approach in docs and code in the repo.

**Comment by mfazekas** [comment]
> Also there seems to be a mix of usages in importing the components in the repo. Which is prefered: `<MapView />` or ` <MapboxGL.MapView />`. Would probably be easier for beginners if it's a more unified approach in docs and code in the repo.

I'd personally prefer just `MapView`

**Comment by KiwiKilian** [comment]
Thanks, I also prefer using it without `MapboxGL`. Do you have any input to this @mfazekas?

> - I can't a find a way to properly type the `ref` in `Earthquakes.ts`?
> - What is the successor of `SymbolLayerStyle` if it's deprecated?

**Comment by mfazekas** [comment]
> Thanks, I also prefer using it without `MapboxGL`. Do you have any input to this @mfazekas?
> 
> > * I can't a find a way to properly type the `ref` in `Earthquakes.ts`?

```typescript
let shapeSource = useRef<ShapeSource>();
...

<ShapeSource
   ref={shapeSource}
   ...
 />
```

should work.

> > * What is the successor of `SymbolLayerStyle` if it's deprecated?

Hmm good question. You should be able to use `SymbolLayer['props']['style']`. Maybe we should keep SymbolLayerStyle around

**Comment by KiwiKilian** [comment]
I found the problem in the `index.d.ts`, `Camera` does it like this:
```ts
const Camera = _Camera;
type Camera = _Camera;
```

The type definition for `ShapeSource` was missing. Correct usage is now:
```ts
const shapeSource = useRef<ShapeSource>(null);
```

I would also be supporting keeping all styles as a separate type.


Now only one problem still occurs, which was already present before I touched anything. On iOS the clusterProperties are not working, while Android is working fine:
```
Mapbox error RCTMGLShapeSource.parsing clusterProperties failed - error: The data couldn’t be read because it isn’t in the correct format. typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "Expected to decode String but found an array instead.", underlyingError: nil)) {"level": "error", "message": "RCTMGLShapeSource.parsing clusterProperties failed - error: The data couldn’t be read because it isn’t in the correct format. typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: \"Index 0\", intValue: 0)], debugDescription: \"Expected to decode String but found an array instead.\", underlyingError: nil))"}
```

We could merge now, as this problem was there before and I open an issue with this problem, the actual purpose of this MR is done. If you have a quick idea I can try it, but Swift is not my home ground.

**Comment by mfazekas** [comment]
> I found the problem in the `index.d.ts`, `Camera` does it like this:
> 
> ```ts
> const Camera = _Camera;
> type Camera = _Camera;
> ```
> 
> The type definition for `ShapeSource` was missing. Correct usage is now:
> 
> ```ts
> const shapeSource = useRef<ShapeSource>(null);
> ```
> 
> I would also be supporting keeping all styles as a separate type.
> 
> Now only one problem still occurs, which was already present before I touched anything. On iOS the clusterProperties are not working, while Android is working fine:
> 
> ```
> Mapbox error RCTMGLShapeSource.parsing clusterProperties failed - error: The data couldn’t be read because it isn’t in the correct format. typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "Expected to decode String but found an array instead.", underlyingError: nil)) {"level": "error", "message": "RCTMGLShapeSource.parsing clusterProperties failed - error: The data couldn’t be read because it isn’t in the correct format. typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: \"Index 0\", intValue: 0)], debugDescription: \"Expected to decode String but found an array instead.\", underlyingError: nil))"}
> ```
> 
> We could merge now, as this problem was there before and I open an issue with this problem, the actual purpose of this MR is done. If you have a quick idea I can try it, but Swift is not my home ground.

Unfortunately this is a known upstream issue - https://github.com/mapbox/mapbox-maps-ios/issues/1571

**Pull request merged**
