### PR TITLE
Add `requestsAlwaysUse` prop to the UserLocation

### PR DESCRIPTION
**Pull request by pablogdcr**
## Description

Added `requestsAlwaysUse` prop to the UserLocation component that allows choosing if we want to listen for the user location in the background or not.
It allows us to not ask for background location permission when we don't need it and still use the UserLocation component.

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [x] I updated the documentation with running `yarn generate` in the root folder
- [x] I updated the typings files - if js interface was changed (`index.d.ts`)
- [ ] I added/ updated a sample - if a new feature was implemented (`/example`)

## Screenshot OR Video

None for now.

### CODE REVIEW

**Comment by mfazekas** [comment]
Thanks much, sounds interesting. Can you actually receive events in background?

**Comment by mfazekas** [comment]
I'd actually prefer naming it requestAlwayUse rather than `listensToLocationInBackground` as I assume receiving location updates is much more difficult, due to the background nature of the task.

**Comment by pablogdcr** [comment]
There are several additional steps to follow in order to listen to the location in the background.
So yes you're right, `requestAlwaysUse` seems more appropriate. I will continue working on this next week and keep you posted!

**Review by mfazekas — APPROVED** [review]

**Comment by mfazekas** [comment]
@pablogdcr can you look into test failures

**Comment by pablogdcr** [comment]
@mfazekas fixed. I also tested on Android and made some adjustments

**Comment by swey** [comment]
Thanks @pablogdcr for your work! Hoping for this adjustment to come to the next release version!

**Review by mfazekas — APPROVED** [review]

**Comment by csimpi** [comment]
@pablogdcr @mfazekas 
This is not working at all.
1) Not requesting the permission even if it's true
2) I've added the permission plugin, and set it up perfectly, location permission is requested and enabled, but when I put the app in the background the location tracking stops. I tried to log it to a file, I get nothing when the app is in the BG. 

So this feature is meaningless in this format I am afraid.

There should be documentation added or just remove it, because this misled feature mislead our team.

**Pull request merged**
