### PR TITLE
Prevent possible crash on add/remove layer

### PR DESCRIPTION
**Pull request by naftalibeder**
Fixes a potential crash (not always reproducible, but reminiscent of crashes I used to get pre-v10) that generally has this shape

> Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: MapboxMaps.StyleError(rawValue: "my-cool-layer-id does not exist")

In general, I think this library should avoid crashing at all costs, meaning gracefully handling exceptions when possible.

### CODE REVIEW

**Review by mfazekas — CHANGES_REQUESTED** [review]
I prefer `try!` to `try?` as silencing an error is worse than crashing in my opinion.  `try with catch and logging is` probably ideal as it will not silence the error, but is not a crash.

**Comment by mfazekas** [comment]
> Fixes a potential crash (not always reproducible, but reminiscent of crashes I used to get pre-v10) that generally has this shape
> 

BTW do you see such crashes after #1839 ?!

**Comment by naftalibeder** [comment]
> silencing an error is worse than crashing in my opinion

Our users might disagree, but I understand the idea. 😆 

> BTW do you see such crashes after https://github.com/rnmapbox/maps/pull/1839 ?!

Yeah, I got this in testing while fully synced with `main` this morning.

Anyway, I can update to catch and log the errors, no problem.

**Comment by naftalibeder** [comment]
@mfazekas Done, seem OK?

**Review by mfazekas — APPROVED** [review]

**Comment by mfazekas** [comment]
> @mfazekas Done, seem OK?

👍

**Pull request merged**
