### PR TITLE
feat: migrate RNMBXPointAnnotation to new arch

### PR DESCRIPTION
**Pull request by WoLewicki**
PR migrating `RNMBXPointAnnotation` to new arch and cleaning native ref resolving to be used with turbomodule.

### CODE REVIEW

**Comment by WoLewicki** [comment]
@mfazekas I added the migration of `Callout` and `MarkerView` since they seemed connected to the `PointAnnotation`, and also pushed a small fix for `Atmosphere`. Is it ok? I'll also make a separate PR for some fixes in `Sources` since I forgot to do one thing there and another PR for the generic `ViewTagResolver`.

**Comment by WoLewicki** [comment]
@mfazekas can you elaborate what is `TileSource`? I see its implementations in native code, but there is no such component on the TS side.

**Comment by WoLewicki** [comment]
Oh it looks like it is just an abstract class, nvm.

**Review by mfazekas — APPROVED** [review]

**Comment by WoLewicki** [comment]
@mfazekas  Ok so this one if ready to be merged 🚀

**Pull request merged**
