### PR TITLE
Add ability to set projection

### PR DESCRIPTION
**Pull request by SkySails**
## Description

Relates to #2125

Added ability to set projection (`globe`/`mercator`) when using the Mapbox v10 SDK.

Supported platforms (todo):
 - [x] IOS
 - [x] Android
 
 ### Notes

~This _seems_ to be working poorly together with `MarkerView`. Not sure why yet.~ - Seems to be fixed in recent updates!

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [x] I updated the documentation with running `yarn generate` in the root folder
- [x] I updated the typings files - if js interface was changed (`index.d.ts`)a
- [x] I added/ updated a sample - if a new feature was implemented (`/example`)

## Screenshot OR Video

Simulator  10-13

### CODE REVIEW

**Review by mfazekas — APPROVED** [review]
Thanks it looks nice, we'd need to add to `index.d.ts` as well.

**Comment by SkySails** [comment]
Thanks! I'll work on achieving the same on the android side of things as well.

> We'd need to add to index.d.ts as well.

Do we need anything other than [this](https://github.com/SkySails/maps/blob/feat/allow-setting-projection/index.d.ts#L529)?

**Comment by mfazekas** [comment]
> Thanks! I'll work on achieving the same on the android side of things as well.
> 
> > We'd need to add to index.d.ts as well.
> 
> Do we need anything other than [this](https://github.com/SkySails/maps/blob/feat/allow-setting-projection/index.d.ts#L529)?

Nope that is great, thanks!

**Comment by SkySails** [comment]
@mfazekas Finally had some time to finish this! Would you mind having another look?

**Pull request merged**
