### PR TITLE
Warn instead of crashing on `onDidFinishRenderingMap` error

### PR DESCRIPTION
**Pull request by naftalibeder**
I was getting an array-as-string type conversion error on the line with `mManager.receiveCommand(...)`. I don't have time to look more deeply into it, but this at least prevents a crash while delivering a warning.

### CODE REVIEW

**Comment by mfazekas** [comment]
> I was getting an array-as-string type conversion error on the line with `mManager.receiveCommand(...)`. I don't have time to look more deeply into it, but this at least prevents a crash while delivering a warning.

It would be great if you could post the full stack trace.

**Comment by naftalibeder** [comment]
> It would be great if you could post the full stack trace.

Sure, see below:

```kotlin
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: Unhandled SoftException
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeArray cannot be cast to java.lang.String
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:102)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.receiveCommand(RCTMGLMapViewManager.java:293)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.receiveCommand(RCTMGLMapViewManager.java:40)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.dispatchCommand(NativeViewHierarchyManager.java:831)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchCommandOperation.executeWithExceptions(UIViewOperationQueue.java:323)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:879)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1035)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at android.view.Choreographer.doFrame(Choreographer.java:775)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at android.os.Handler.handleCallback(Handler.java:938)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at android.os.Looper.loopOnce(Looper.java:201)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at android.os.Looper.loop(Looper.java:288)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at java.lang.reflect.Method.invoke(Native Method)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-27 09:52:45.488  8569  8569 E unknown:UIViewOperationQueue: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-27 09:52:45.516   682   951 W BtGatt.ScanManager: Moving scan client to opportunistic (scannerId 6)
05-27 09:52:45.518   682   958 E bt_btm  : system/bt/main/bte_logmsg.cc:191 LogMsg: BTM_BleObserve Observe not active
05-27 09:52:45.539   326   326 D goldfish-address-space: claimShared: Ask to claim region [0x1f6690000 0x1f6f64000]
05-27 09:52:45.587   326   326 D goldfish-address-space: claimShared: Ask to claim region [0x1f8000000 0x1f88d4000]
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: Exception in onDidFinishRenderingMap
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeArray cannot be cast to java.lang.String
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:102)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at com.mapbox.rctmgl.components.mapview.RCTMGLMapViewManager.receiveCommand(RCTMGLMapViewManager.java:293)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at com.mapbox.rctmgl.components.mapview.RCTMGLMapView.onDidFinishRenderingMap(RCTMGLMapView.java:754)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishRenderingMap(MapChangeReceiver.java:170)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishRenderingMap(NativeMapView.java:1092)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at android.os.MessageQueue.next(MessageQueue.java:335)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at android.os.Looper.loopOnce(Looper.java:161)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at android.os.Looper.loop(Looper.java:288)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at java.lang.reflect.Method.invoke(Native Method)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-27 09:52:45.590  8569  8569 E Mbgl-MapChangeReceiver: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
05-27 09:52:45.593  8569  8680 E ReactNativeJS: 'Mapbox error', 'Exception in onDidFinishRenderingMap', { level: 'error',
05-27 09:52:45.593  8569  8680 E ReactNativeJS:   tag: 'Mbgl-MapChangeReceiver',
05-27 09:52:45.593  8569  8680 E ReactNativeJS:   message: 'Exception in onDidFinishRenderingMap' }
```

**Comment by mfazekas** [comment]
Based on the stack this is not an issue with `preRenderMethod` but with `METHOD_SET_HANDLED_MAP_EVENTS` handler, or the way it's called.

https://github.com/rnmapbox/maps/blob/44ebee935f463c2cafcd96748e19e13d71682821/android/rctmgl/src/main/java-mapboxgl/common/com/mapbox/rctmgl/components/mapview/RCTMGLMapViewManager.java#L289-L297

And likely caused by this change:
https://github.com/rnmapbox/maps/commit/640ea612604fdb8dcf1e7df8870bddaf25467256#diff-6ddd9b54ec1c85c312cc9203ea907c300fad8e954469cf7aa43ef28ce789b6b5R404-R406

I'll add a fix for the root cause.

**Review by mfazekas — APPROVED** [review]
ok as temp solution until I fix the real issue

**Comment by naftalibeder** [comment]
@mfazekas Ok, done.

**Comment by wiedymi** [comment]
@mfazekas when do you plan to merge it?

**Pull request merged**
