### PR TITLE
convert mapview to kotlin

### PR DESCRIPTION
**Pull request by felixgourdeau**
## Migrate MapView to kotlin

In order to use all of the v10 api, we need to convert some part of the java codebase to kotlin. This PR is aimed at converting the `MapView` class to kotlin (using the `Convert Java File to Kotlin File` tool from Android Studio).

I had to convert a bunch of other class to Kotlin (Callout, MarkerView, PointAnnotation, Image, NativeUserLocation, Light, AbstractSouceConsumer, Source and LocationManager) to avoid `unresolved supertypes error`.

I also had to rename `src/main/java` to `src/main/java-legacy` in order to avoid `Check your module classpath for missing or conflicting dependencies` error. It seems that code in `src/main/java` was included in the v10 build. I'm not sure about the impact of this change on the `v8` and the `maplibre` flavor.

## Checklist

- [ ] I have tested this on a device/simulator for each compatible OS
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typings files (`index.d.ts`)
- [ ] I added/ updated a sample (`/example`)

### CODE REVIEW

**Comment by mfazekas** [comment]
@felixgourdeau thank much for the PR.

Kotlin is something we'd like to adopt on the long run. Right now we can use java to consume v10 api.  

I've did an attempt to migrate some class to kotlin, but I was getting `unresolved supertypes` build errors in certain circumstances. Which sounded like more a compiler bug than a legit error, so I had to revert my PR.

See: https://github.com/rnmapbox/maps/pull/1784, https://github.com/rnmapbox/maps/pull/1797

**Comment by felixgourdeau** [comment]
Thanks for your feedback @mfazekas !

I don't think we can use java for all of the v10 api, we need to switch to kotlin, at least for mapview.

The `unresolved supertypes` error you had in the CI mean that you also had to convert these class to kotlin in order to make it work. For example, `unresolved supertypes: MarkerViewManager` mean that `MarkerViewManager` also need to be converted to kotlin. That is why I had to convert more than one java file to kotlin, and not just `MapView`.

Also, you had a bunch of `Check your module classpath for missing or conflicting dependencies` error. It is caused by the `main` buildFlavor (located in src/main/java) that seems to be always included in the build, even with `java.srcDirs = ['src/main/java-v10']`. That is why I renamed `src/main/java` to `src/main/java-legacy`.

I totally agree with you about being gradual, and I am open to suggestion.

**Comment by mfazekas** [comment]
> The unresolved supertypes error you had in the CI mean that you also had to convert these class to kotlin in order to make it work. For example, unresolved supertypes: MarkerViewManager mean that MarkerViewManager also need to be converted to kotlin. That is why I had to convert more than one java file to kotlin, and not just MapView.

Hm, ... Possible, but not sure why I have not seen it locally just on CI.

> Also, you had a bunch of Check your module classpath for missing or conflicting dependencies error. It is caused by the main buildFlavor (located in src/main/java) that seems to be always included in the build, even with java.srcDirs = ['src/main/java-v10']. That is why I renamed src/main/java to src/main/java-legacy.

Also possible, will confirm that, thanks.

https://github.com/rnmapbox/maps/runs/5574375183?check_suite_focus=true

> I totally agree with you about being gradual, and I am open to suggestion.

Feel free to open smallest PR possible that builds, then we can go on from there.

**Comment by felixgourdeau** [comment]
> Hm, ... Possible, but not sure why I have not seen it locally just on CI. 

I had to `./gradlew clean` before building to make it fail locally

> Feel free to open smallest PR possible that builds, then we can go on from there.

I'll reopen the PR to test it in the CI

**Comment by mfazekas** [comment]
@felixgourdeau thanks.

I've added a reorganisation PR at #1884, as that's easier to review without the kotlin changes.

You were right about the `java` directory included in classpath, in case kotlin is used, so we have to move java. I've moved `java` -> `java-mapboxgl/common` and `java-mapbox` -> `java-mapboxgl/mapbox`, `java-maplibre` to `java-mapboxgl/maplibre`.

Another issue for kotlin was that AbstractMapFeature was in wrong directory, that should be fixed as well.

**Comment by mfazekas** [comment]
@felixgourdeau I've remerged RCTMGLTerrain in kotlin to main, it compiles fine now thanks to rename from `src/main/java` and fix of package in `AbstractMapFeature`. 

Can you submit PR-s for different components, so we can progress with Kotlin conversion.

Sorry for the trouble and thanks much for the help in adopting kotlin.

**Comment by felixgourdeau** [comment]
@mfazekas no problem. I'll close this PR and open a new PR with your java file reorg.

Thanks for your help

**Pull request closed without merging**
