### PR TITLE
fix(android): add maven central above jcenter due to the deprecation and flakey behavior

### PR DESCRIPTION
**Pull request by joshua-smith4**
## Description

Related to #1711 
Related to #1707 

## Checklist

- [X] I have tested this on a device/simulator for each compatible OS
- [X] I formatted JS and TS files with running `yarn lint:fix` in the root folder
- [X] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typings files (`index.d.ts`)
- [ ] I added/ updated a sample (`/example`)

### CODE REVIEW

**Comment by shay-te** [comment]
Thanks. seems like jcenter is up now. from my build failure, looking at the log seems like there are missing dependencies on mavencentral.  

```
Could not determine the dependencies of task ':react-native-mapbox-gl_maps:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-mapbox-gl_maps:debugCompileClasspath'.
   > Could not find com.facebook.yoga:proguard-annotations:1.14.1.
     Required by:
         project :react-native-mapbox-gl_maps > com.facebook.react:react-native:0.64.2
   > Could not find com.facebook.fbjni:fbjni-java-only:0.0.3.
     Required by:
         project :react-native-mapbox-gl_maps > com.facebook.react:react-native:0.64.2
   > Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
     Required by:
         project :react-native-mapbox-gl_maps > com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

The seems like the dependencies are missing on maven central 


- `com.facebook.yoga:proguard-annotations` has only version `1.19.0`
   https://search.maven.org/artifact/com.facebook.yoga/proguard-annotations 

-  `com.facebook.fbjni:fbjni-java-only` is missing version `0.0.3`
   https://search.maven.org/artifact/com.facebook.fbjni/fbjni-java-only

- `com.mapbox.mapboxsdk:mapbox-android-accounts`
   dose not exists on maven central

**Comment by Carmelo992** [comment]
Are there any updates? 
I saw that `com.facebook.fbjni:fbjni-java-only` and `com.facebook.yoga:proguard-annotations` are available now.

Instead, for com.mapbox.mapboxsdk:mapbox-android-accounts, probably it must downloaded from mapbox repo, using dedicated credentials.

Here the link to the documentation: https://docs.mapbox.com/android/maps/guides/install/#configure-credentials

**Comment by naftalibeder** [comment]
Not totally following, but seems like this is now moot? I’m going to close this, but feel free to reopen an issue if it’s still a problem.

**Comment by shay-te** [comment]
> Not totally following, but seems like this is now moot? I’m going to close this, but feel free to reopen an issue if it’s still a problem.

Thank you for looking at this. it could be easily tested by removing the `jcenter` from the Gradle file.

**Pull request closed without merging**
