### PR TITLE
feat(expo,ios): add RNMapboxMapsVersion to Expo Plugin on iOS

### PR DESCRIPTION
**Pull request by KiwiKilian**
## Description

Fixes: #2618 (iOS only, as RNMapboxMapsVersion not yet implemented on Android)

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [x] I updated the documentation with running `yarn generate` in the root folder
- [ ] I added/updated a sample - if a new feature was implemented (`/example`)

### CODE REVIEW

**Review by mfazekas — APPROVED** [review]

**Comment by ryanpwaldon** [comment]
Hey @KiwiKilian, I think this may need some more work – my builds are failing when `RNMapboxMapsVersion` is left unset. When I set the version, it works fine.

**Comment by KiwiKilian** [comment]
@ryanpwaldon thanks for the report. On which platform does it fail?

**Comment by ryanpwaldon** [comment]
@KiwiKilian I've only tested iOS. Sorry, I'm not setup for Android atm 😅

**Comment by ryanpwaldon** [comment]
Thanks @KiwiKilian ✨

**Pull request merged**
