### PR TITLE
v10 iOS: Fix additional memory leaks

### PR DESCRIPTION
**Pull request by mysport12**
## Description

Fixed additional vars that should be weak

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I updated the typings files - if js interface was changed (`index.d.ts`)
- [ ] I added/ updated a sample - if a new feature was implemented (`/example`)

### CODE REVIEW

**Review by mfazekas — APPROVED** [review]

**Comment by EasonHeee** [comment]
Hi folks @mysport12 @mfazekas , thanks for fixing this. But we are seeing same memory leak behavior on IOS simulator every time when we reopen the IOS simulator with Expo the mem usage will increase by 300MB. I think this is a serious problem. Could you double check this is fixed? I attached some screen shot for mem increase without doing anything else but just reopen IOS simulator from Expo and re-launch our App. 

**Mapbox Implementation**
Mapbox

**Platform**
iOS

**@rnmapbox/maps version**
10.0.0-beta.62

**Standalone component to reproduce**
import MapboxGL from '@react-native-mapbox-gl/maps'
import * as React from 'react'
import { View } from 'react-native'
import { Footer } from '../components'

export default function MapStripped() {
  return (
    <View style={{ flex: 1 }}>
      <MapboxGL.MapView styleURL="mapbox://styles/mapbox/streets-v11" style={{ flex: 1 }} />
      <Footer />
    </View>
  )
}

Thanks, let us know if you have any thoughts. Some screen shots from our side. 

First Launch of our App - Mem Usage 550 MB
image

Second Launch - 805 MB
image

Third Launch - 1200 MB
image

Forth Launch - 1500 MB
image

Fifth Launch - 1870 MB
image

Sixth Launch - 2100 MB
image

Seventh Launch - 2470 MB
image

**Comment by mfazekas** [comment]
@EasonHeee so just to clarify this is an issue on expo when reloading the the javascript in the app without restarting the native part, right?!

**Comment by EasonHeee** [comment]
Hi @mfazekas thanks for checking. 1. React Native Expo and RNMap, 2. Load the Mapview 3. Run expo run:ios 4. Press m to see toggle performance monitor with mem usage info 5. Press i to reopen IOS app. You should see the the mem increase each time when you press i

**Comment by Daviddavidov98** [comment]
Having the same issue here, using  React Native Expo and RNMap as well. Any updates/workarounds?

**Comment by mfazekas** [comment]
@Daviddavidov98 Can you open a new issue? And please make sure you include a compoent that can be used to reproduce the issue. THanks

**Comment by Daviddavidov98** [comment]
@mfazekas Just added! #3068

**Pull request merged**
