### PR TITLE
MapLibre support

### LINKED ISSUE #1472: Build issue for ios in MGLModule.m Multiple Errors - MapLibre SDK
---------  

**Describe the bug**  
The IOS Build Process fails with multiple errors in MGLModule.m after adding react-native-mapbox lib and installing pods

**To Reproduce**  
- npx react-native init MapTest
- yarn add @react-native-mapbox-gl/maps
- adjust podfile (like below)
- pod install
- open workspace file with XCode 12.5.1 and run build

**Podfile**:
```js
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MapTest' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'MapTestTests' do
    inherit! :complete
    # Pods for testing
  end

  $RNMBGL_Use_SPM = true

    pre_install do |installer|
      $RNMBGL.pre_install(installer)
    end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
     $RNMBGL.post_install(installer)
  end
end
```

**Expected behavior**  
Build runs successfully

**Actual behavior**  
Build fails with multiple errors in **MGLModule.m**

```js
 // style urls
    NSMutableDictionary *styleURLS = [[NSMutableDictionary alloc] init];
    [styleURLS setObject:[MGLStyle.streetsStyleURL absoluteString] forKey:@"Street"];
    [styleURLS setObject:[MGLStyle.darkStyleURL absoluteString] forKey:@"Dark"];
    [styleURLS setObject:[MGLStyle.lightStyleURL absoluteString] forKey:@"Light"];
    [styleURLS setObject:[MGLStyle.outdoorsStyleURL absoluteString] forKey:@"Outdoors"];
    [styleURLS setObject:[MGLStyle.satelliteStyleURL absoluteString] forKey:@"Satellite"];
    [styleURLS setObject:[MGLStyle.satelliteStreetsStyleURL absoluteString] forKey:@"SatelliteStreet"];
....
RCT_EXPORT_METHOD(setAccessToken:(NSString *)accessToken)
{
    [MGLAccountManager setAccessToken:accessToken];
}
```
Errors:
- Property 'streetsStyleURL' not found on object of type 'MGLStyle' (line 30-35)
- occurring for all attributes of MGLStyle object
- Use of undeclared identifier 'MGLAccountManager' (line 243+258)

Bildschirmfoto 2021-07-26 um 15 57 44

**Versions (please complete the following information):**  
 - Platform: iOS
 - Platform OS:  iOS 10
 - Device: IPhone 12 mini
 - Emulator/ Simulator: yes
 - Dev OS: OSX 11.4
 - react-native-mapbox-gl Version 8.2.1
 - Mapbox GL version 5.9.0
 - React Native Version 0.63.4

**Additional context**  
Build run on XCode 12.5.1

### PR DESCRIPTION
**Pull request by mfazekas**
## Description

Fixes #1472

MapLibre 5.12 support

Note the following should be added to Podfile for `MapLibre 5.12` support.

```pod file
$RNMGL_USE_MAPLIBRE = true
```

### CODE REVIEW

**Comment by ferdicus** [comment]
thanks @mfazekas 🙇🏿 
Will test this coming friday 👍🏿

**Comment by doylemark** [comment]
> ```js
>  ERROR  Mapbox error Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600001743f00> {"filePath": "-[MGLNetworkConfiguration errorLog:]", "level": "error", "line": 129, "message": "Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600001743f00>"}
>  ERROR  Mapbox error [event]:Setup [code]:-1 [message]:loading style failed: unsupported URL {"filePath": "virtual bool mbgl::MGLCoreLoggingObserver::onRecord(mbgl::EventSeverity, mbgl::Event, int64_t, const std::string &)", "level": "error", "line": 30, "message": "[event]:Setup [code]:-1 [message]:loading style failed: unsupported URL"}
>  ERROR  Mapbox error Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600001743f00> {"filePath": "-[MGLNetworkConfiguration errorLog:]", "level": "error", "line": 129, "message": "Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600001743f00>"}
>  ERROR  Mapbox error [event]:Style [code]:-1 [message]:Failed to load source composite: unsupported URL {"filePath": "virtual bool mbgl::MGLCoreLoggingObserver::onRecord(mbgl::EventSeverity, mbgl::Event, int64_t, const std::string &)", "level": "error", "line": 30, "message": "[event]:Style [code]:-1 [message]:Failed to load source composite: unsupported URL"}
> ```

 @ferdicus The errors you mention here, I *believe* are caused by URLs prefixed "mapbox://" being interpreted as file paths.. Similar to "file://". On device iOS the style completely fails to load when these errors occur however 🤔

**Comment by go-sean-go** [comment]
@doylemark Did you ever solve the above? I'm on rnmapbox 8.5.0 + mapLibre 5.12.1. Same problem whether I implement `$ReactNativeMapboxGLIOSVersion = '~> 6.4.1'` or not.

I'm really fascinated by your observation on the file path - is there a solve?

**Comment by go-sean-go** [comment]
> tested with `styleUrl` pointed to mapbox (`'mapbox://styles/mapbox/dark-v10'`) with a valid accesstoken and got these errors. Not sure if related though 😕 Maybe just logger spam - posting nevertheless
> 
> ```js
>  ERROR  Mapbox error Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600001743f00> {"filePath": "-[MGLNetworkConfiguration errorLog:]", "level": "error", "line": 129, "message": "Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600001743f00>"}
>  ERROR  Mapbox error [event]:Setup [code]:-1 [message]:loading style failed: unsupported URL {"filePath": "virtual bool mbgl::MGLCoreLoggingObserver::onRecord(mbgl::EventSeverity, mbgl::Event, int64_t, const std::string &)", "level": "error", "line": 30, "message": "[event]:Setup [code]:-1 [message]:loading style failed: unsupported URL"}
>  ERROR  Mapbox error Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600001743f00> {"filePath": "-[MGLNetworkConfiguration errorLog:]", "level": "error", "line": 129, "message": "Requesting: Requesting: %@ failed with error: %@ failed with error: <MGLNetworkConfiguration: 0x600001743f00>"}
>  ERROR  Mapbox error [event]:Style [code]:-1 [message]:Failed to load source composite: unsupported URL {"filePath": "virtual bool mbgl::MGLCoreLoggingObserver::onRecord(mbgl::EventSeverity, mbgl::Event, int64_t, const std::string &)", "level": "error", "line": 30, "message": "[event]:Style [code]:-1 [message]:Failed to load source composite: unsupported URL"}
> ```

@ferdicus - I'm having this on my project now (see versions above) - in my case, it's preventing the map tiles from rendering/loading at all. Wondering whether you have any new intel on this since your post ~6 months ago?

Symptoms are that the map is not loading at all - though it's misleading because some devices will load it from a local cache. New installs on new devices always fail to render the map, however.

I'm on Apple Silicon - the root of all trouble & joy. ;)

**Pull request merged**
